"""content version material dependency keyed by version not artifact

Revision ID: fb5e3889277c
Revises: 6bc000bb178d
Create Date: 2026-08-25 17:53:15.412432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb5e3889277c'
down_revision: Union[str, None] = '6bc000bb178d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_version_material_dependencies',
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('content_version_id', 'material_id')
    )
    op.create_index('ix_content_version_material_dependencies_material_id', 'content_version_material_dependencies', ['material_id'], unique=False)
    op.drop_index('ix_artifact_material_dependencies_material_id', table_name='artifact_material_dependencies')
    op.drop_table('artifact_material_dependencies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_material_dependencies',
    sa.Column('artifact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name='artifact_material_dependencies_artifact_id_fkey'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='artifact_material_dependencies_material_id_fkey'),
    sa.PrimaryKeyConstraint('artifact_id', 'material_id', name='artifact_material_dependencies_pkey')
    )
    op.create_index('ix_artifact_material_dependencies_material_id', 'artifact_material_dependencies', ['material_id'], unique=False)
    op.drop_index('ix_content_version_material_dependencies_material_id', table_name='content_version_material_dependencies')
    op.drop_table('content_version_material_dependencies')
    # ### end Alembic commands ###
