"""initial schema

Revision ID: fdbd31cee7f9
Revises: 
Create Date: 2026-08-25 17:21:08.923595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fdbd31cee7f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('result_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('external_ref', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref')
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_observations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('applicable_track', sa.String(length=255), nullable=True),
    sa.Column('scope_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mechanism_summary', sa.String(length=4096), nullable=True),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('owner_ref', sa.String(length=255), nullable=True),
    sa.Column('analysis_authorized', sa.Boolean(), nullable=False),
    sa.Column('generation_authorized', sa.Boolean(), nullable=False),
    sa.Column('publish_authorized', sa.Boolean(), nullable=False),
    sa.Column('scope_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_ref', sa.String(length=1024), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playbooks',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('proposed_by', sa.String(length=255), nullable=True),
    sa.Column('scope_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observation_status', sa.String(length=1024), nullable=True),
    sa.Column('rationale', sa.String(length=4096), nullable=True),
    sa.Column('supersedes_playbook_id', sa.UUID(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_membership_user_ws')
    )
    op.create_table('accounts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'handle', name='uq_account_platform_handle')
    )
    op.create_table('cycles',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('baseline_capacity', sa.Numeric(), nullable=True),
    sa.Column('baseline_capacity_source', sa.String(length=255), nullable=True),
    sa.Column('actual_capacity', sa.Numeric(), nullable=True),
    sa.Column('actual_capacity_source', sa.String(length=255), nullable=True),
    sa.Column('expected_publish_count', sa.Numeric(), nullable=True),
    sa.Column('expected_publish_count_source', sa.String(length=255), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_cycle_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['supersedes_cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_overrides',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_start', sa.DateTime(), nullable=False),
    sa.Column('scope_end', sa.DateTime(), nullable=True),
    sa.Column('targeted_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('artifacts',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parent_artifact_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_run_states',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('last_success_step', sa.String(length=255), nullable=True),
    sa.Column('failed_step', sa.String(length=255), nullable=True),
    sa.Column('resumable_from', sa.String(length=255), nullable=True),
    sa.Column('side_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('task_snapshots',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('info_nature', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('confirmation_status', sa.String(length=32), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('artifact_material_dependencies',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('artifact_id', 'material_id')
    )
    op.create_table('content_versions',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('content_ref', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('produced_by', sa.String(length=255), nullable=True),
    sa.Column('promoted_by', sa.String(length=255), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('was_selected', sa.Boolean(), nullable=False),
    sa.Column('was_produced', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'version_no', name='uq_version_artifact_no')
    )
    op.create_table('publish_instances',
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('registered_by', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('feedback_records',
    sa.Column('publish_instance_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('is_manual_entry', sa.Boolean(), nullable=False),
    sa.Column('is_pre_publish_review', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('goal_at_the_time', sa.String(length=1024), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publish_instance_id'], ['publish_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_records')
    op.drop_table('publish_instances')
    op.drop_table('content_versions')
    op.drop_table('artifact_material_dependencies')
    op.drop_table('task_snapshots')
    op.drop_table('task_run_states')
    op.drop_table('artifacts')
    op.drop_table('tasks')
    op.drop_table('campaign_overrides')
    op.drop_table('cycles')
    op.drop_table('accounts')
    op.drop_table('workspace_memberships')
    op.drop_table('subjects')
    op.drop_table('playbooks')
    op.drop_table('materials')
    op.drop_table('market_observations')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
